`r paste('#', basename(filelist[[i]]), '{data-navmenu="TDReport Filename"}')`

`r shiny::tags$h2(basename(filelist[[i]]), style="text-align:center")`

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

```{r setup, include=FALSE}

library(flexdashboard)
library(shiny)
library(shinydashboard)
library(magrittr)
library(stringr)
library(purrr)
library(dplyr)
library(UpSetR)
library(ggplot2)
library(DT)
library(plotly)
library(ggthemes)
library(viridis)
library(waffle)

# Plotly parameters

download_button_params <- 
  list(
    format = "svg"
  )

# ggplot themes

col_plot_theme <- 
  list(
    theme_minimal(),
    theme(
      axis.text.x = element_text(angle = 90),
      panel.grid.major.x = element_blank()
    )
  )

heatmap_theme <- 
  list(
    theme_minimal(),
    theme(
      text = element_text(size=16)
    ) 
  )

```

### Best Protein Hits

```{r echo=FALSE}

results_protein[[i]] %>%
  dplyr::select(
    -c(
      "SEQUENCE", "ORGANISM",
      "ORGANISM-ID", "FUNCTION",
      "SUBCELLULAR-LOCATIONS", "GO_term",
      "GO-ID", "ENTRY-NAME")
  ) %>%
  dplyr::select("UNIPROTKB", "PROTEIN-NAMES", everything()) %>% 
  mutate(filename = sub('(^[^_]+_[^_]+_[^_]+)_(.*)$', '\\1_ \\2', filename)) %>%
  mutate(
    `PROTEIN-NAMES` = 
      stringr::str_trunc(`PROTEIN-NAMES`, 60, "right", ellipsis = "..."
      )
  ) %>% 
  mutate(GlobalQvalue = formatC(GlobalQvalue, format = "e", digits = 3)) %>%
  mutate(GRAVY = formatC(GRAVY, format = "f", digits = 3)) %>% 
  mutate(MonoisotopicMass = formatC(MonoisotopicMass, format = "f", digits = 4)) %>% 
  mutate(AverageMass = formatC(AverageMass, format = "f", digits = 4)) %>% 
  DT::datatable(
    extensions = c("FixedColumns", "Buttons"),
    class = "hover",
    options = list(
      pageLength = 10,
      lengthMenu = c(10, 25),
      pagingType = "full_numbers",
      columnDefs = list(list(className = 'dt-center')),
      dom = "Bfrtip",
      scrollX = FALSE,
      buttons = c("copy", "csv", "excel", "colvis")
    )
  ) %>% 
  DT::formatStyle(
    1:length(results_protein[[i]]),
    fontSize = "9",
    digits = 3
  )

```

### Protein Counts

```{r}

plot <- 
  results_protein[[i]] %>% 
  group_by(fraction) %>% 
  summarise("protein count" = n()) %>%
  ggplot() +
  geom_col(
    aes(fraction, `protein count`),
    color = "black",
    fill = "#4C4184",
    size = 0.25
  ) +
  labs(
    x = "Fraction",
    y = "Protein Count"
  ) +
  col_plot_theme

p1 <- 
  plotly::ggplotly(plot) %>% 
  plotly::config(
    displaylogo = FALSE,
    toImageButtonOptions = download_button_params
  ) %>% 
  plotly::layout(
    xaxis = list(
      tickfont = list(
        size = 12
      )
    )
  )


plot <- 
  results_protein[[i]] %>% 
  group_by(filename) %>% 
  summarise("protein count" = n()) %>%
  mutate(filename = sub('(^[^_]+_[^_]+_[^_]+)_(.*)$', '\\1_ \\2', filename)) %>% 
  # mutate(filename = stringr::str_trunc(filename, 40, side = "left")) %>%
  ggplot() +
  geom_col(
    aes(filename, `protein count`),
    color = "black",
    fill = "#4C4184",
    size = 0.25
  ) +
  labs(
    x = "Filename",
    y = "Protein Count"
  ) +
  guides(
    color = "none",
    fill = "none"
  ) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 8)) +
  col_plot_theme

p2 <- 
  plotly::ggplotly(plot) %>% 
  plotly::config(
    displaylogo = FALSE,
    toImageButtonOptions = download_button_params
  ) %>% 
  plotly::layout(
    xaxis = list(
      tickfont = list(
        size = 8
      )
    )
  )

shinydashboard::tabBox(
  width = 1000,
  id = "tabset1",
  tabPanel("By Fraction", p1),
  tabPanel("By Filename", p2)
)

```

### Protein Heatmaps

```{r}

bin_size <- 1000   # SPECIFY SIZE for heatmap mass bins
bins <-  seq.int(0, 200000, by = bin_size)

protein_heatmap_data <- 
  results_protein[[i]] %>% 
  select(c("ObservedPrecursorMass", "fraction")) %>% 
  mutate(mass_bin = cut(ObservedPrecursorMass, breaks = bins, labels = FALSE)) %>%
  group_by(fraction, mass_bin) %>% 
  summarize("Protein Count" = n()) %>%
  mutate(mass_bin =  (mass_bin * bin_size) - bin_size) %>% 
  ungroup() %>% 
  mutate(fraction = forcats::as_factor(fraction))

protein_heatmap <- 
  protein_heatmap_data %>% 
  ggplot(
    aes(
      mass_bin/1000, 
      fraction,
      fill = `Protein Count`
    )
  ) +
  geom_tile() +
  scale_fill_viridis_c(option = "C", direction = -1) +
  xlim(
    0,
    plyr::round_any(
      max(protein_heatmap_data$mass_bin/1000),
      10, f = ceiling
    )
  ) +
  scale_y_discrete(limits = rev(levels(protein_heatmap_data$fraction))) +
  labs(
    x = "Mass Bin (kDa)",
    y = "Fraction"
  ) +
  heatmap_theme

# print(protein_heatmap)

plotly::ggplotly(protein_heatmap) %>% 
  plotly::config(
    displaylogo = FALSE,
    toImageButtonOptions = download_button_params
  )



```

### Protein Waffle Plots

```{r}

counts_byfrac_fltrd <- 
  results_protein_countsbyfraction %>%
  filter(tdreport_name == basename(filelist[[i]]))

fractionlist <- 
  counts_byfrac_fltrd %>% 
  .$fraction %>%
  as.list

waffledata_protein_all_byfraction <- 
  tibble(
    Localization = factor(
      c(
        rep("Cytosolic", length(fractionlist)),
        rep("Membrane", length(fractionlist)),
        rep("Periplasmic", length(fractionlist)),
        rep("NOTA", length(fractionlist))
      )
    ),
    Count = c(counts_byfrac_fltrd$cytosol_count,
              counts_byfrac_fltrd$membrane_count,
              counts_byfrac_fltrd$periplasm_count,
              counts_byfrac_fltrd$NOTA_count),
    fraction = rep(counts_byfrac_fltrd$fraction, 4)
  ) %>%
  group_by(fraction, Localization) %>% 
  summarize(Count)

output <- 
  waffledata_protein_all_byfraction %>%
  ggplot(aes(fill = Localization, values = Count)) +
  waffle::stat_waffle(color = "white", size = 0.35, n_rows = 10,
                      flip = TRUE, geom = "tile") +
  facet_wrap(~fraction, nrow = 1, strip.position = "bottom") +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_continuous(labels = function(x) x * 10, # this multiplier must be equal to n_rows above
                     expand = c(0,0)) +
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal() +
  labs(
    x = "Fraction Number",
    y = "Protein Count"
  ) +
  theme_minimal() +
  theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  guides(fill = guide_legend("Localization", reverse = TRUE))

print(output)

# plotly::ggplotly(output, originalData = FALSE, tooltip = "Localization")

```

### Best Proteoform Hits

```{r}

results_proteoform[[i]] %>%
  dplyr::select(
    -c(
      "ORGANISM",
      "ORGANISM-ID", "FUNCTION",
      "SUBCELLULAR-LOCATIONS", "GO_term",
      "PROTEIN-NAMES", "GO-ID", "fraction"
    )
  ) %>%
  mutate(filename = sub('(^[^_]+_[^_]+_[^_]+)_(.*)$', '\\1_ \\2', filename)) %>% 
  mutate(GlobalQvalue = formatC(GlobalQvalue, format = "e", digits = 2)) %>%
  mutate(GRAVY = formatC(GRAVY, format = "f", digits = 3)) %>% 
  mutate(MonoisotopicMass = formatC(MonoisotopicMass, format = "f", digits = 4)) %>% 
  mutate(AverageMass = formatC(AverageMass, format = "f", digits = 4)) %>% 
  DT::datatable(
    extensions = c("FixedColumns", "Buttons"),
    class = "hover",
    options = list(
      pageLength = 10,
      lengthMenu = c(10, 25),
      pagingType = "full_numbers",
      columnDefs = list(list(className = 'dt-center')),
      dom = "Bfrtip",
      scrollX = FALSE,
      buttons = c("copy", "csv", "excel", "colvis")
    )
  ) %>% 
  DT::formatStyle(
    1:length(results_proteoform[[i]]),
    fontSize = "9",
    digits = 3
  )
```

### Proteoform Heatmaps

```{r}

bin_size <- 1000   # SPECIFY SIZE for heatmap mass bins
bins <-  seq.int(0, 200000, by = bin_size)

proteoform_heatmap_data <- 
  results_proteoform[[i]] %>% 
  select(c("ObservedPrecursorMass", "fraction")) %>% 
  mutate(mass_bin = cut(ObservedPrecursorMass, breaks = bins, labels = FALSE)) %>%
  group_by(fraction, mass_bin) %>% 
  summarize(n()) %>%
  mutate(mass_bin =  (mass_bin * bin_size) - bin_size) %>% 
  rename("Proteoform Count" = `n()`) %>%
  ungroup() %>% 
  mutate(fraction = forcats::as_factor(fraction))

proteoform_heatmap <- 
  proteoform_heatmap_data %>% 
  ggplot(aes(mass_bin, fraction,
             fill = `Proteoform Count`)) +
  geom_tile() +
  scale_fill_viridis_c(option = "C", direction = -1) +
  xlim(0,
       plyr::round_any(
         max(proteoform_heatmap_data$mass_bin),
         10000, f = ceiling)
  ) +
  scale_y_discrete(limits = rev(levels(proteoform_heatmap_data$fraction))) +
  labs(x = "Mass Bin (Da)",
       y = "Fraction") +
  theme_minimal() +
  theme(text = element_text(size=18))

print(proteoform_heatmap)

# plotly::ggplotly(proteoform_heatmap)

```


